version: '3.2'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
  nginx:
    image: 'nginx:latest'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3499:80'