version: "3.2"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - BASE_URL=http://localhost:3050/api
      - PORT=3050
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./angular-src
    volumes:
      - ./angular-src:/app
      - /app/node_modules
    environment:
      - apiUrl=http://localhost:3050/api
      - apiPrefix=api
      - dashBoardTitle=app work in docker
  nginx:
    image: "nginx:latest"
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
