version: '3.2'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./angular-src
    volumes:
      - ./angular-src:/app
      - /app/node_modules
    # ports: 
    #   - '4200:4200' 
    # environment: 
    #   - CHOKIDAR_USEPOLLING=true   
  nginx:
    image: 'nginx:latest'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
        - api
        - client